name: Add issues to LESPROJEKT Hub Project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project-hub:
    name: Add issue to project Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/LESPROJEKT/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
  add-to-project-dev-team:
    name: Add issue to project Development Team
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/LESPROJEKT/projects/7
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
